sudo: false
language: node_js
node_js: '6'
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    rooms:
      secure: pML6/DUd6YeeKicthV5SJTwgCdGKLWI2lf0UzcE/ToPlkGmAJ1RHFDJmWAtKkMoH2E7EsAyV/TPnXoOgmhqpuOL1HGh7WDAo+Lg34pHHB4KH6K3Dl1Jh9a4d0KL22S52rOQaiUyd6LN7nuaWg09fTLMpDNqbsnMoiR8B8Uyn8agf9NGt387OjwJN/FY1mw5p5VcCXFaF5QQF3pFk2O6eD2jZZ+YL9U73nb8hdvaqHx+keGD1zUIwRlpsILaPcVoD3kZVkeeeTKt9FtD0QR4g/3yj1XuC5D/CeaICmGCQnR8A1KnOxxptXNiiDdgN+fNO6bWq3z9FGnKPlFZG/J8XGilDi21CkRgoSjK43AJo8I7IGnLkL0HyIDIA5pbTjpZRO1vE1WT8wjY4Iye3FOm3jSEN4+ZqNIHQc0HbhDOTtxOHLrzrGRs3a54XPwHJdaTlY7ZaSSIlcyodIR0ijCSZXsWfnhH5aTjjI4ndVEaJi6Ah1ACSMkCzbUCTCXDC6v/QvZDWDPVEjIH0YWBy+JqacTWOmtYvZ8/w05Xx/V/WlhTrsSgNG1+tzUTnSQP30ng005hK+/4xpEfV0AS/WCFUcUoOFPICVzDAXP3/Ibpk/uSahOjV+kOUQIHdRqk5ppqThI9OLZ1V9k6vWTD6b+elNgIf05sLJhQtQjRom7r4crw=
    on_success: change
    on_failure: always
after_success:
- |
  if [[ $TRAVIS_BRANCH == 'master' || $TRAVIS_PULL_REQUEST == 'true' ]]; then
    npm run coverage;
    npm run coverage:upload;
  fi
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
  - gh-pages
